import { DeepOmitAutoGenerated } from '../../../../domain/shared/types';
import SongAggregate from '../../../../domain/songAggregate/songAggregate';

export interface CreateSongInput extends DeepOmitAutoGenerated<SongAggregate> {}
