import { AutoGenerated, DeepProcess } from '../../../../domain/shared/types';
import SongAggregate from '../../../../domain/songAggregate/songAggregate';

export interface UpdateSongInput extends DeepProcess<SongAggregate, AutoGenerated, 'id'> { }
