export type Id = string;

export type Tag = string;

export interface DataKey {
  id: Id;
}

export type AutoGenerated = 'id' | 'createdTimestamp' | 'updatedTimestamp';

export type DeepPartial<T> = T extends object
  ? {
      [P in keyof T]?: DeepPartial<T[P]>;
    }
  : T;

export type DeepPartialOmit<T, K extends string> = T extends (infer R)[]
  ? DeepPartialOmit<R, K>[]
  : T extends object
    ? {
        [P in keyof T]?: P extends K ? T[P] : DeepPartialOmit<T[P], K>;
      }
    : T;

export type DeepPartialOmitAutoGenerated<T> = DeepPartialOmit<T, AutoGenerated>;

export type DeepProcess<T, OmitK extends string, RequireK extends string> = T extends (infer R)[]
  ? DeepProcess<R, OmitK, RequireK>[]
  : T extends object
    ? {
        [P in keyof T as P extends OmitK | RequireK ? never : P]?: DeepProcess<
          T[P],
          OmitK,
          RequireK
        >;
      } & {
        [P in keyof T as P extends RequireK ? P : never]-?: DeepProcess<T[P], OmitK, RequireK>;
      }
    : T;

export type DeepOmit<T, K extends string> = T extends (infer R)[]
  ? DeepOmit<R, K>[]
  : T extends object
    ? {
        [P in keyof T as P extends K ? never : P]: DeepOmit<T[P], K>;
      }
    : T;

export type DeepOmitAutoGenerated<T> = DeepOmit<T, AutoGenerated>;
