import { AutoGenerated, DeepProcess, Id } from '../shared/types';
import NoteEntity from './noteEntity';

interface NoteRepository {

  create(note: NoteEntity): Promise<NoteEntity>;

  update(song: DeepProcess<NoteEntity, AutoGenerated, 'id'>): Promise<NoteEntity>;

  findById(id: Id): Promise<NoteEntity | null>;

  deleteById(id: Id): Promise<boolean>;

  findByTrackId(trackId: Id): Promise<NoteEntity[]>;

}

export default NoteRepository;