import NoteEntity from '../../domain/note/noteEntity';
import NoteRepository from '../../domain/note/noteRepository';
import { AutoGenerated, DeepProcess, Id } from '../../domain/shared/types';
import NoteMapper from '../mapper/noteMapper';
import { createNoteOther, deleteNote, findNotesBySong, updateNote } from '../services/api';

export class NoteRepositoryImpl implements NoteRepository {

  async create(note: NoteEntity): Promise<NoteEntity> {
    const result = await createNoteOther(note.trackId, note);
    return NoteMapper.toDomain(result);
  }

  async update(note: DeepProcess<NoteEntity, AutoGenerated, 'id'>): Promise<NoteEntity> {
    const { id, ...noteToUpdate } = note;
    const result = await updateNote(id, noteToUpdate);
    return NoteMapper.toDomain(result);
  }

  findById(id: Id): Promise<NoteEntity | null> {
    throw new Error('Method not implemented.');
  }

  deleteById(id: Id): Promise<boolean> {
    return deleteNote(id);
  }

  async findBySongId(songId: Id): Promise<NoteEntity[]> {
    const result = await findNotesBySong(songId);
    return result.map(NoteMapper.toDomain);
  }

  findByTrackId(trackId: Id): Promise<NoteEntity[]> {
    throw new Error('Method not implemented.');
  }

}