import { AutoGenerated, DeepProcess, Id } from '../../domain/shared/types';
import SongAggregate from '../../domain/songAggregate/songAggregate';
import SongAggregateRepository from '../../domain/songAggregate/songAggregateRepository';
import SongMapper from '../mapper/songMapper';
import {
  createSong,
  deleteSong,
  fetchAllSongs,
  fetchSongDetails,
  updateSong,
} from '../services/api';

export class SongAggregateRepositoryImpl implements SongAggregateRepository {
  async create(song: SongAggregate): Promise<SongAggregate> {
    const result = await createSong(song);
    return SongMapper.toSongAggrate(result);
  }

  async update(song: DeepProcess<SongAggregate, AutoGenerated, 'id'>): Promise<SongAggregate> {
    const result = await updateSong(song);
    return SongMapper.toSongAggrate(result);
  }

  async findById(id: Id): Promise<SongAggregate> {
    const song = await fetchSongDetails(id);
    return SongMapper.toSongAggrate(song);
  }

  async findAll(): Promise<SongAggregate[]> {
    const response = await fetchAllSongs();
    return response.map(song => SongMapper.toSongAggrate(song));
  }

  async deleteById(id: Id): Promise<boolean> {
    return deleteSong(id);
  }
}
