import { LocalStorageSongRepository } from './infrastructure/storage/LocalStorageSongRepository';
import { LocalStorageNoteRepository } from './infrastructure/storage/LocalStorageNoteRepository';
import { ListAllSongs } from './application/song/ListAllSong';
import { CreateNewSong } from './application/song/CreateNewSong';
import { EditSong } from './application/song/EditSong';
import { DeleteSong } from './application/song/DeleteSong';
import { LoadSongById } from './application/song/LoadSongById';
import { ImportSongFromJsonUseCase } from './application/song/ImportSongFromJson';
import { ExportSongToJsonUseCase } from './application/song/ExportSongToJson';
import { EditTrackLabelUseCase } from './application/track/EditTrackLabel';
import { AddNoteToSong } from './application/note/AddNoteToSong';
import { DeleteExistingNote } from './application/note/DeleteExistingNote';
import { EditExistingNote } from './application/note/EditExistingNote';
import { ListNotesInSong } from './application/note/ListNotesInSong';

export const songRepo = new LocalStorageSongRepository();
export const noteRepo = new LocalStorageNoteRepository();
export const listAllSongsUseCase = new ListAllSongs(songRepo);
export const createNewSongUseCase = new CreateNewSong(songRepo);
export const editSongUseCase = new EditSong(songRepo);
export const deleteSongUseCase = new DeleteSong(songRepo);
export const loadSongByIdUseCase = new LoadSongById(songRepo);
export const importSongFromJsonUseCase = new ImportSongFromJsonUseCase(songRepo, noteRepo);
export const exportSongToJsonUseCase = new ExportSongToJsonUseCase();
export const editTrackLabelUseCase = new EditTrackLabelUseCase(songRepo);
export const addNoteToSongUseCase = new AddNoteToSong(noteRepo, songRepo);
export const deleteExistingNoteUseCase = new DeleteExistingNote(noteRepo, songRepo);
export const editExistingNoteUseCase = new EditExistingNote(noteRepo, songRepo);
export const listNotesInSongUseCase = new ListNotesInSong(noteRepo);