import { AutoGenerated, DeepProcess, Id } from '../shared/types';
import SongAggregate from './songAggregate';

interface SongAggregateRepository {
  create(song: SongAggregate): Promise<SongAggregate>;

  update(song: DeepProcess<SongAggregate, AutoGenerated, 'id'>): Promise<SongAggregate>;

  findById(id: Id): Promise<SongAggregate>;

  findAll(): Promise<SongAggregate[]>;

  deleteById(id: Id): Promise<boolean>;
}

export default SongAggregateRepository;
