import NoteEntity from '../../../domain/note/noteEntity';
import NoteRepository from '../../../domain/note/noteRepository';
import { AutoGenerated, DeepProcess } from '../../../domain/shared/types';
import BaseUseCase from '../baseUseCase';

class UpdateNoteUseCase extends BaseUseCase<
  DeepProcess<NoteEntity, AutoGenerated, 'id'>,
  NoteEntity
> {
  private noteRepository: NoteRepository;

  constructor(noteRepository: NoteRepository) {
    super();

    this.noteRepository = noteRepository;
  }

  handle(data: DeepProcess<NoteEntity, AutoGenerated, 'id'>) {
    return this.noteRepository.update(data);
  }
}

export default UpdateNoteUseCase;
